# Declare the configuration for the server like the application default
server:
  port: 8446
logging:
  file: /java/OCP_LOGS/ocp-ui-api/ocp-ui-api.log
info:
  component: OCP UI API
ribbon:
  ReadTimeout: 50000
  listOfServers: ${OCP_UI_API_FIS_ENPOINT:http://ocp-fis:8444}
hystrix.command.default.execution.timeout.enabled: false
# Include changes according to the uaa profile
security:
  name: uaa
  oauth2:
    client:
      access-token-uri: https://iam.mynjinck.com/auth/realms/njinck-dev/protocol/openid-connect/token
ocp:
  ocp-ui-api:
    oauth2:
      authorization-server-endpoint: https://iam.mynjinck.com/auth/realms/njinck-dev
      users-password-server-endpoint: https://iam.mynjinck.com/auth/admin/realms/njinck-dev/users
      authorization-configuration: https://iam.mynjinck.com/auth/realms/njinck-dev/.well-known/openid-configuration
      autohirization-client-id: ocpUiApi
      authorization-client-secret: ed5bf849-b699-4b11-8118-aac796d8db2f
      authorization-redirect-url: ${OCP_UI_API_AUTHORIZATION_REDIRECT_ENDPOINT:http://localhost:3000}/ocp-ui-api/receiver
      authorization-redirect-ui: ${OCP_UI_API_AUTHORIZATION_REDIRECT_ENDPOINT:http://localhost:3000}/ocp-ui/login
feign-client:
  auth:
    form-encoded-client:
      name: uaaForm
    rest-client:
      name: uaaRest
    user-token-rest-client:
      name: uaaUserTokenRestClient

feign:
  client: 
    config:
      default:
        connectTimeout: 720000
        readTimeout: 720000

smart:
  core-url: http://localhost:8445
tableau:
  remote_ip: 10.64.0.138
