server:
  port: 8082
spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/fhir'
    #url: jdbc:h2:mem:test_mem
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver
    max-active: 15
  profiles:
    ### This is the FHIR version. Choose between, dstu2, dstu3, r4 or r5
    active: r4
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.search.model_mapping: ca.uhn.fhir.jpa.search.LuceneSearchMappingFactory
      hibernate.format_sql: false
      hibernate.show_sql: false
      hibernate.hbm2ddl.auto: update
      hibernate.jdbc.batch_size: 20
      hibernate.cache.use_query_cache: false
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_structured_entries: false
      hibernate.cache.use_minimal_puts: false
      hibernate.search.default.directory_provider: filesystem
      hibernate.search.default.indexBase: /data/hapi/lucenefiles
      hibernate.search.lucene_version: LUCENE_CURRENT
  batch:
    job:
      enabled: false
hapi:
  fhir:
    fhir_version: R4
    defer_indexing_for_codesystems_of_size: 101
    allow_external_references: true
    allow_multiple_delete: true
    auto_create_placeholder_reference_targets: false
    enforce_referential_integrity_on_delete: false
    enforce_referential_integrity_on_write: false
    expunge_enabled: true
    client_id_strategy: any
    graphql_enabled: true

    allowed_bundle_types:
      - document
      - message
      - transaction
      - transaction-response
      - batch
      - batch-response
      - history
      - searchset
      - collection
    tester:
      home:
        id: home
        name: Local Tester
        server_address: 'http://localhost:8082/fhir'
        refuse_to_fetch_third_party_urls: false
        fhir_version: R4
      global:
        name: Global Tester
        server_address: "http://hapi.fhir.org/baseR4"
        refuse_to_fetch_third_party_urls: false
        fhir_version: R4
    subscription:
      resthook_enabled: true
      websocket_enabled: true
      email:
        from: <hapi4-development@yourdomain.com>
        host: <mailhost>
        port: 25
